### ISSUE TITLE
[Tracking issue] General dataset support

### ISSUE THREAD

**Issue by qgallouedec** [huggingface/trl#2071]
The aim is for all trainers to apply the same procedure in their init function:

- if needed, apply the chat template, then
- if needed, tokenize.

### Standard dataset

  - [x] `BCOTrainer`
  - [x] `CPOTrainer`
  - [x] `DPOTrainer`
  - [x] `GKDTrainer` (same as `SFTTrainer`)
  - [x] ~`IterativeSFTTrainer`~ removed
  - [x] `KTOTrainer`
  - [x] `NashMDTrainer`
  - [x] `OnlineDPOTrainer`
  - [x] `ORPOTrainer`
  - [ ] `PPOTrainer`
  - [x] `RewardTrainer` #2102
  - [x] `RLOOTrainer` #3801 
  - [x] `SFTTrainer` (could be previously achieved via `"dataset_text_field"`) #2078; #2405
  - [x] `XPOTrainer`

### Conversational dataset

  - [x] `BCOTrainer` #2107
  - [x] `CPOTrainer` #2144
  - [x] `DPOTrainer` #2131
  - [x] `GKDTrainer`
  - [x] ~`IterativeSFTTrainer`~ removed
  - [x] `KTOTrainer` #2248
  - [x] `NashMDTrainer` #2075
  - [x] `OnlineDPOTrainer` #2075
  - [x] `ORPOTrainer` #2184
  - [ ] `PPOTrainer`
  - [x] `RewardTrainer` #2102
  - [x] `RLOOTrainer` #3801
  - [x] `SFTTrainer` (yes, via `get_formatting_func_from_dataset` for now, needs refactoring); refactor in #2405
  - [x] `XPOTrainer` #2075

### Misc

- [x] Update `docs/dataset_format.mdx`
